# auto pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bc-auto-pv
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "127.0.0.1"
    path: "/home/nfs_data"

# namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: bc-auto

# auto pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-auto-pvc
  namespace: bc-auto
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Mi
  volumeName: bc-auto-pv

#auto deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bc-auto
  name: bc-auto
  labels:
    app: cluster
    role: bc-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster
      role: bc-auto
  template:
    metadata:
      labels:
        app: cluster
        role: bc-auto
    spec:
      dnsPolicy: ClusterFirst
      hostAliases:
      - ip: 127.0.0.1
        hostnames:
        - "bc.auto.com"
      containers:
      - name: bc-auto
        image: bc/auto:1.0-SNAPSHOT
        workingDir: /data
        ports:
        - containerPort: 60000
        env:
        - name: LANG
          value: "C.UTF-8"
        # version list: V1.4.0, V1.4.5
        - name: KLEDGER_VERSION
          value: "V1.4.5"

        # kledger auto name
        - name: KLEDGER_AUTO_NAME
          value: "kledger-auto"
        # kledger config
        - name: KLEDGER_LOG_LEVEL
          value: "info"
        - name: KLEDGER_TLS_ENABLE
          value: "true"
        - name: KLEDGER_DB_MODE
          value: "couchdb"
        command:
        - /bin/bash
        - -c
        - java -jar /work/auto/auto-1.0-SNAPSHOT.jar
        # - sleep 360000
        volumeMounts:
          - name: storage
            mountPath: "/data"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: bc-auto-pvc


# kledger-auto service
---
apiVersion: v1
kind: Service
metadata:
  namespace: bc-auto
  name: bc-auto
  labels:
    app: cluster
    role: bc-auto
spec:
  # clusterIP: None
  type: NodePort
  selector:
    app: cluster
    role: bc-auto
  ports:
    - name: auto
      port: 60000
      protocol: TCP
      targetPort: 60000
      nodePort: 30000
